services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pharma'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/Users/liqiang/postgresql/data

volumes:
  pgdata: