apiVersion: v1
kind: Service
metadata:
  name: {{ include "pharmaflow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pharmaflow.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "pharmaflow.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http